apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fjvlb666
  name: fjvlb666
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: fjv-finalapp
  type: NodePort
status:
  loadBalancer: {}
